<<<<<<< HEAD
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
=======
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
>>>>>>> 7439dfe7c2468a723421522cda71625047c7e986
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'